blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://lyzev.github.io/discord
    about: For assistance with minor concerns, feel free to join our supportive community on the Discord server. Our friendly members and staff are ready to help you.
